[project]
authors = ["Jeongseok Lee <jeongseok@meta.com>"]
channels = ["conda-forge"]
name = "libtorch-example"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[build-dependencies]
cmake = ">=3.31.6,<4"
pybind11 = ">=2.13.6,<3"

[dependencies]
pytorch = ">=2.6.0,<3"

[tasks]
rm-build = { cmd = "rm -rf build" }
config ={ cmd = "cmake -S . -B build" }

#=========
# win-64
#=========

[target.win-64.dependencies]

[target.win-64.tasks]
config = { cmd = """
    cmake \
        -S . \
        -B build/$PIXI_ENVIRONMENT_NAME/cpp \
        -G 'Visual Studio 17 2022' \
        -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
        -DBUILD_SHARED_LIBS=OFF
    """ }

build = { cmd = "cmake --build build/$PIXI_ENVIRONMENT_NAME/cpp -j --config Release", depends-on = [
    "config",
] }

#==============
# Feature: CPU
#==============

[feature.cpu]

#==============
# Feature: GPU
#==============

[feature.gpu]
platforms = ["linux-64", "win-64"]
system-requirements = { cuda = "12" }
build-dependencies = { cuda-toolkit = ">=12.6.3,<13", cuda-nvtx-dev = ">=12.6.3,<13" }
dependencies = { python = "3.12.*", pytorch-gpu = ">=2.6.0,<3", cuda-nvtx-dev = ">=12.6.3,<13" }

#==============
# Environments
#==============

[environments]
gpu = ["gpu"]
cpu = ["cpu"]
default = ["cpu"]
