[project]
authors = ["Jeongseok Lee <jeongseok@meta.com>"]
channels = ["conda-forge"]
name = "libtorch-example"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[dependencies]

[tasks]
config ={ cmd = "cmake -S . -B build" }

#==============
# Feature: CPU
#==============

[feature.cpu.dependencies]
libtorch = { version = ">=2.5.1,<3", build = "*cpu*" }

#==============
# Feature: GPU
#==============

[feature.gpu]
platforms = ["linux-64", "win-64"]
system-requirements = { cuda = "12" }
dependencies = { python = "3.12.*", libtorch = { version = ">=2.5.1,<3", build = "*cuda*" }, cuda-toolkit = ">=12.6.3,<13" }

#==============
# Environments
#==============

[environments]
gpu = ["gpu"]
cpu = ["cpu"]
default = ["cpu"]
